export { TextH1 } from './TextH1'
export { TextH4 } from './TextH4'
export { TextH6 } from './TextH6'

export { TextH1Bold, TextH1BoldPrimary, TextH1BoldNeutral80 } from './TextH1Bold'
export { TextH4Bold, TextH4BoldPrimary, TextH4BoldNeutral80 } from './TextH4Bold'
export { TextH6Bold, TextH6BoldPrimary, TextH6BoldNeutral80 } from './TextH6Bold'
export { TextBody1, TextBody1Neutral80, TextBody1Neutral60, TextBody1Primary } from './TextBody1'
export { TextLink, TextLinkPrimary } from './TextLink'
export { TextTimestamp } from './TextTimestamp'
